# Generated by Django 5.2.1 on 2025-07-31 16:44

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='petstagram', validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
