# Generated by Django 5.2.1 on 2025-07-31 16:54

import cloudinary.models
import photos.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[photos.validators.FileSizeValidator(5)]),
        ),
    ]
